#!/usr/bin/env python3
"""Bake the 32 NFL team logos into the app as small data URIs (src/js/02b-team-logos.js).

Why: NFL_LOGO() used to fetch desktop-sized transforms from NFL's CDN — 32 network
images every time the team dropdown opened, slow and flaky on mobile. Baked at 48px
they total well under 150KB, render instantly, and work offline. Rerun whenever a
team rebrands; the CDN stays as the runtime fallback for any code not baked."""
import base64, io, os, sys, urllib.request
try:
    from PIL import Image
except ImportError:
    sys.exit("needs PIL (run with the pyenv nfl interpreter)")

TEAMS = ["ARI","ATL","BAL","BUF","CAR","CHI","CIN","CLE","DAL","DEN","DET","GB","HOU","IND",
         "JAX","KC","LA","LAC","LV","MIA","MIN","NE","NO","NYG","NYJ","PHI","PIT","SEA","SF","TB","TEN","WAS"]
URL = "https://static.www.nfl.com/t_headshot_desktop/f_auto/league/api/clubs/logos/{c}"
SIZE = 48

out = {}
total = 0
for c in TEAMS:
    cdn = URL.format(c="JAC" if c == "JAX" else c)
    req = urllib.request.Request(cdn, headers={"User-Agent": "triplecrown-build"})
    with urllib.request.urlopen(req, timeout=30) as r:
        raw = r.read()
    im = Image.open(io.BytesIO(raw)).convert("RGBA")
    im.thumbnail((SIZE, SIZE), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "WEBP", quality=82, method=6)
    b = buf.getvalue()
    if len(b) > 8000:  # webp should never be this big at 48px; keep the file honest
        sys.exit(f"{c}: {len(b)}B — too big, inspect")
    out[c] = "data:image/webp;base64," + base64.b64encode(b).decode()
    total += len(b)
    print(f"  {c}: {len(b)}B")

js = ("// GENERATED by tools/bake_team_logos.py — 32 team logos as 48px webp data URIs.\n"
      "// NFL_LOGO() (01-constants.js) prefers these; the CDN remains the fallback.\n"
      "const TEAM_LOGO_DATA = {\n"
      + "".join(f'  {c}: "{u}",\n' for c, u in out.items())
      + "};\n")
open(os.path.join(os.path.dirname(__file__), "..", "src", "js", "02b-team-logos.js"), "w").write(js)
print(f"baked {len(out)} logos, {total/1024:.0f}KB total → src/js/02b-team-logos.js")
